Algoritmo "teste"

// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Miguel
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Lucas Augusto
// Data atual  : 18/10/2024

Var
   number : inteiro
   divisao : inteiro
   
Inicio
   number <- 28
   divisao <- number % 7
   enquanto number < 60  faca
      escreval(number)
      number <- number + 7
   fimenquanto
   
Fimalgoritmo

